### ISSUE TITLE
Maintenance Status of the "rbenchmark" Package

### ISSUE THREAD

**Issue by BerriJ** [eddelbuettel/rbenchmark#1]
I hope you are doing well!

I am currently working on an article focused on benchmarking R code. As part of my research, I’ve been exploring various packages available in the R ecosystem, and your package, rbenchmark, caught my attention.

I noticed that the last commit to the repository was made around nine years ago, and the documentation seems to be offline. I wanted to reach out to inquire whether the package is still under active maintenance or if it has been retired.

Understanding the current status of rbenchmark would be very helpful for my article, as I aim to provide readers with an up-to-date overview of the tools available for benchmarking in R.

Thank you in advance for your time, and I look forward to hearing from you.

**Comment by eddelbuettel** [comment]
Well I am not the maintainer as the CRAN page will tell.  I may once have helped, hence this (inactive, unused) repo.  I will close this; you may have better luck with the maintainer.  Or not.  I mostly moved on to microbenchmark, but this package still works too.
